package com.vrushank.bottomupavafirst;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2020-07-10T11:41:45.233+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "PaymentProcessorImplService", 
                  wsdlLocation = "file:/C:/Users/Vrushank.Patel/Documents/workspace-spring-tool-suite-4-4.6.2.RELEASE/bottomupavafirst-client/src/main/resources/wsdl/paymentProcessor.wsdl",
                  targetNamespace = "http://bottomupavafirst.vrushank.com/") 
public class PaymentProcessorImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bottomupavafirst.vrushank.com/", "PaymentProcessorImplService");
    public final static QName PaymentProcessorImplPort = new QName("http://bottomupavafirst.vrushank.com/", "PaymentProcessorImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Vrushank.Patel/Documents/workspace-spring-tool-suite-4-4.6.2.RELEASE/bottomupavafirst-client/src/main/resources/wsdl/paymentProcessor.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PaymentProcessorImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Vrushank.Patel/Documents/workspace-spring-tool-suite-4-4.6.2.RELEASE/bottomupavafirst-client/src/main/resources/wsdl/paymentProcessor.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentProcessorImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentProcessorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentProcessorImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentProcessorImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentProcessorImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentProcessorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PaymentProcessor
     */
    @WebEndpoint(name = "PaymentProcessorImplPort")
    public PaymentProcessor getPaymentProcessorImplPort() {
        return super.getPort(PaymentProcessorImplPort, PaymentProcessor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentProcessor
     */
    @WebEndpoint(name = "PaymentProcessorImplPort")
    public PaymentProcessor getPaymentProcessorImplPort(WebServiceFeature... features) {
        return super.getPort(PaymentProcessorImplPort, PaymentProcessor.class, features);
    }

}
