package com.vrushank.wsdlwsfirst;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.vrushank.ws.trainings.CustomerOrdersPortType;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2020-07-09T17:23:55.681+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "CustomerOrdersWsImplService", 
                  wsdlLocation = "file:/C:/Users/Vrushank.Patel/Documents/workspace-spring-tool-suite-4-4.6.2.RELEASE/wsdlwsfirst-soap-client/src/main/resources/wsdl/CustomerOrdersSoapClient.wsdl",
                  targetNamespace = "http://wsdlwsfirst.vrushank.com/") 
public class CustomerOrdersWsImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsdlwsfirst.vrushank.com/", "CustomerOrdersWsImplService");
    public final static QName CustomerOrdersWsImplPort = new QName("http://wsdlwsfirst.vrushank.com/", "CustomerOrdersWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Vrushank.Patel/Documents/workspace-spring-tool-suite-4-4.6.2.RELEASE/wsdlwsfirst-soap-client/src/main/resources/wsdl/CustomerOrdersSoapClient.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerOrdersWsImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Vrushank.Patel/Documents/workspace-spring-tool-suite-4-4.6.2.RELEASE/wsdlwsfirst-soap-client/src/main/resources/wsdl/CustomerOrdersSoapClient.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerOrdersWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerOrdersWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerOrdersWsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerOrdersWsImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerOrdersWsImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerOrdersWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CustomerOrdersPortType
     */
    @WebEndpoint(name = "CustomerOrdersWsImplPort")
    public CustomerOrdersPortType getCustomerOrdersWsImplPort() {
        return super.getPort(CustomerOrdersWsImplPort, CustomerOrdersPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerOrdersPortType
     */
    @WebEndpoint(name = "CustomerOrdersWsImplPort")
    public CustomerOrdersPortType getCustomerOrdersWsImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerOrdersWsImplPort, CustomerOrdersPortType.class, features);
    }

}
